"use client";
import {useEffect,useMemo,useState} from "react";import {UserButton} from "@clerk/nextjs";
type Entry={id:string,at:string,name:string,units:number};type User={id:string,username:string,email?:string,clerkId:string};
const defaults=["Beer","Wine","Prosecco","Cider","Guinness","Spirits","Cocktail","Other"];
export default function Dashboard({user}:{user:User}){const [entries,setEntries]=useState<Entry[]>([]);const [name,setName]=useState("Beer");const [units,setUnits]=useState("2");const [at,setAt]=useState("");const [busy,setBusy]=useState(true);const [message,setMessage]=useState("");
const total=useMemo(()=>entries.reduce((s,e)=>s+e.units,0),[entries]);useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());setAt(d.toISOString().slice(0,16));fetch("/api/entries").then(r=>r.json()).then(d=>{setEntries(d.entries||[]);setBusy(false)})},[]);
async function add(e:React.FormEvent){e.preventDefault();const n=Number(units);if(!name.trim()||!Number.isFinite(n)||n<=0)return;setBusy(true);const r=await fetch("/api/entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),units:n,at:new Date(at).toISOString()})});const d=await r.json();if(r.ok){setEntries(d.entries);setUnits("2");setMessage("Saved")}else setMessage(d.error||"Could not save");setBusy(false);setTimeout(()=>setMessage(""),1800)}
async function remove(id:string){const r=await fetch("/api/entries?id="+encodeURIComponent(id),{method:"DELETE"});const d=await r.json();if(r.ok)setEntries(d.entries)}
return <main className="app"><header><div><p className="eyebrow">UNIT LOGGER</p><h1>Today, simply logged.</h1></div><div className="headerActions"><UserButton/></div></header><section className="hero"><div><span className="total">{total.toFixed(1)}</span><span className="totalLabel">units logged</span></div><span className="sync">☁ synced</span></section><section className="card addCard"><div className="sectionHead"><div><h2>Add a drink</h2><p className="muted">Use a default or type your own.</p></div>{message&&<span className="saved">{message}</span>}</div><form onSubmit={add}><label>Date & time<input type="datetime-local" value={at} onChange={e=>setAt(e.target.value)} required/></label><label>Drink / unit<select value={defaults.includes(name)?name:"__custom"} onChange={e=>setName(e.target.value==="__custom"?"":e.target.value)}>{defaults.map(x=><option key={x}>{x}</option>)}<option value="__custom">Custom…</option></select></label>{(!defaults.includes(name)||name==="")&&<label>Name<input placeholder="e.g. IPA, large wine" value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Units<input inputMode="decimal" type="number" min="0.1" step="0.1" value={units} onChange={e=>setUnits(e.target.value)} required/></label><button disabled={busy}>+ Add drink</button></form></section><section className="history"><div className="sectionHead"><div><h2>History</h2><p className="muted">{entries.length} logged {entries.length===1?"entry":"entries"}</p></div></div>{busy&&entries.length===0?<p className="muted">Loading…</p>:entries.length===0?<div className="empty">Nothing logged yet. Your first drink goes here.</div>:<div className="entries">{entries.slice().sort((a,b)=>b.at.localeCompare(a.at)).map(e=><article className="entry" key={e.id}><div><strong>{e.name}</strong><span>{new Date(e.at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}</span></div><b>{e.units.toFixed(1)}</b><button aria-label={"Delete "+e.name} onClick={()=>remove(e.id)}>×</button></article>)}</div>}</section><footer>Private data • stored with your Vercel project</footer></main>}
